server:
  port: 8080
spring:
  application:
    name: "Challenge-Nequi-Guatemala"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: postgres  # Cambié el nombre aquí también
    port: 5432
    database: postgres
    schema: public
    username: postgres
    password: s3cret

logging:
  level:
    org.springframework.r2dbc: DEBUG
